### ISSUE TITLE
just-capture-group runs should be one or more

### ISSUE THREAD

**Issue by softwareCobbler** [Jimbly/regex-crossword#17]
Hi, this is neat, having fun at lunch trying to solve it.

Should runs that are just a single capture group, such as the one in the top row `(E|RC|NM)*` be `(E|RC|NM)+`? Or notably the `.*` should be `.+`?

**Comment by Jimbly** [comment]
That's how they were phrased in the original puzzle, perhaps because it gives a bit of a hint that the regexs must be a full match not substring, otherwise most everything would just match.  For a full match, `.*` and `.+` are identical, but I agree that `.+` feels a little more readable to me.  But, since the primary goal of this is just a digital version of the original puzzle, I think it's probably best to leave the clues as-is.
